export const GET_ITEM_FETCH_REQUEST = "GET_ITEM_FETCH_REQUEST";
export const GET_ITEM_FETCH_SUCCESS = "GET_ITEM_FETCH_SUCCESS";
export const GET_ITEM_FETCH_FAILURE = "GET_ITEM_FETCH_FAILURE";
export const UPDATE_PRICE_INVENTORY = "UPDATE_PRICE_INVENTORY";

export const SUPPLIER_INFO_SUCCESS = "SUPPLIER_INFO_SUCCESS";

export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";

export const ADD_TO_CART_MODAL_CLOSE = "ADD_TO_CART_MODAL_CLOSE";

export const CHANGE_PRODUCT_ATTRIBUTES = "CHANGE_PRODUCT_ATTRIBUTES";
export const CHANGE_TITLE_AND_LONGDESC = "CHANGE_TITLE_AND_LONGDESC";

export const SHOW_CONTINUE_MODAL = "SHOW_CONTINUE_MODAL";

export const UNMOUNT_PRODUCT_PAGE = "UNMOUNT_PRODUCT_PAGE";

export const SET_REVIEW_MODAL_STATE = "SET_REVIEW_MODAL_STATE";

export const REQUEST_MAIN_PRODUCT_SKUS_N_SKUIDS =
  "REQUEST_MAIN_PRODUCT_SKUS_N_SKUIDS";
export const SUCECSS_MAIN_PRODUCT_SKUS_N_SKUIDS =
  "SUCECSS_MAIN_PRODUCT_SKUS_N_SKUIDS";
export const FAILURE_MAIN_PRODUCT_SKUS_N_SKUIDS =
  "FAILURE_MAIN_PRODUCT_SKUS_N_SKUIDS";
export const SET_ATTRIBUTES_DETAILS = "SET_ATTRIBUTES_DETAILS";

export const SET_CART_VALIDATION_ERR = "SET_CART_VALIDATION_ERR";

export const POPULATE_ACCESSORY_MODAL = "POPULATE_ACCESSORY_MODAL";

export const CLOSE_ACCESSORY_MODAL = "CLOSE_ACCESSORY_MODAL";
export const GET_MODAL_ITEM_FETCH_REQUEST = "GET_MODAL_ITEM_FETCH_REQUEST";
export const GET_MODAL_ITEM_FETCH_SUCCESS = "GET_MODAL_ITEM_FETCH_SUCCESS";
export const UPDATE_PRODUCT_STOCK_INFO = "UPDATE_PRODUCT_STOCK_INFO";

export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_CUSTOMER_ID = "CHANGE_CUSTOMER_ID";
export const UPDATE_ACCESSORY_INVENTORY = "UPDATE_ACCESSORY_INVENTORY";

export const CHECKBOX_ITEM_SELECTED = "CHECKBOX_ITEM_SELECTED";
